### ISSUE TITLE
Allow installation of dependencies via conda

### ISSUE THREAD

**Issue by tkittel** [mctools/dgcode#10]
This might already be possible, but we should try to find a bullet proof recipe. For now I am collecting notes in this issue.

**Comment by tkittel** [comment]
I have a feeling that in principle this will be very easy, if we completely skip the whole dgdepfixer issue. However, to do that we need to work with vanilla versions of e.g. Geant4 and OpenSceneGraph which might complicate matters. At the very least we need to update Geant4 to a more recent versions (cf. #2)

**Comment by tkittel** [comment]
Playing around, here is an environment.yml which I thnk works (it needs more testing though):

```
name: dgcodetest
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.10
  - clang=14.0.6
  - clangxx=14.0.6
  - compilers
  - numpy
  - matplotlib
  - cmake
  - git
  - gdb
  - valgrind
  - pip
  - pip:
    - ptpython==3.0.20
variables:
  CC: clang
  CXX: clang++
  DGCODE_BOOTSTRAP_SKIP_DGDEPFIXER_CHECK: 1
  URL_DGCODE: git@github.com:mctools/dgcode.git
  URL_DGCODE_VAL: git@github.com:mctools/dgcode_val.git
  URL_DGCODE_DG_PROJECTS: git@github.com:ess-dg/dgcode_projects.git
  URL_DGCODE_DG_PRIVATE_PROJECTS: git@github.com:mctools/dgcode_private_projects.git
```

It needs DGCODE_BOOTSTRAP_SKIP_DGDEPFIXER_CHECK support in bootstrap.sh and different python detection, which is WIP in the tk_devel branch.
